### ISSUE TITLE
No hardware files

### ISSUE THREAD

**Issue by sampablokuper** [keepkey/keepkey-firmware#10]
https://www.keepkey.com lists "open source" as one of KeepKey's features. Are the hardware design files (CAD, Gerber, PCB layout, etc) publicly available? If so, where? Or is the hardware closed source?

_N.B. Please feel free to close this as an invalid bug, as it isn't strictly related to the firmware. However, it would be great to have an answer. Thanks!_

**Comment by dstanchfield** [comment]
The hardware is not open source.  That said, we can make accommodations for reviewers / auditors.
