### ISSUE TITLE
Can't apply to support page. Can't send tokens

### ISSUE THREAD

**Issue by NukeManDan** [keepkey/keepkey-firmware#113]
I can not apply to the support : https://keepkey.zendesk.com/hc/en-us
`verification error`

I am able to send ETH.

I am unable to send any tokens from the same account - I get the full dialog on the keepkey w/ pin entry, but after confirming the tx, the chrome app hangs and nothing shows up on any block explorers. 

Please advise.

**Comment by NukeManDan** [comment]
Using:
- Brave as base browser w/ chrome extension.
- Arch Linux

**Comment by keepkeyjon** [comment]
Use the beta firmware. There's an issue with how the current prod firmware handles gas limits / gas fees.

**Comment by keepkeyjon** [comment]
> I can not apply to the support : https://keepkey.zendesk.com/hc/en-us
> `verification error`

You can also email support: support@keepkey.zendesk.com
