### ISSUE TITLE
adding segwit(Litecoin) to your wallets?

### ISSUE THREAD

**Issue by briannyeko** [keepkey/keepkey-firmware#14]
When will you add Segwit on Litecoin to your wallets now when it´s activated?

**Comment by gabrieldov** [comment]
Yeah, that would be great. Trezor already added to their latest firmware update and are working on the wallet interface as well (available on public beta)

**Comment by ngmiller** [comment]
Segwit support for both Bitcoin and Litecoin is something we are looking into supporting as soon as we can. Thank you for your patience as we work through implementing this major change, as well as other improvements!

**Comment by keepkeyjon** [comment]
This is supported in the firmware as of `v5.8.0`.
