### ISSUE TITLE
electron.js app?

### ISSUE THREAD

**Issue by briannyeko** [keepkey/keepkey-firmware#15]
When will you offer a electron.js app(Mac OS,Windows & Linux) now when Chrome will restrict their app section to chromebooks only?

**Comment by ngmiller** [comment]
Hi @briannyeko. This is on our roadmap as we understand the implications of the Chrome team making this decision. I am closing out this issue as it does not relate to the firmware directly. Rest assured that we are working to the resolve this and please don't hesitate to reach out to us on social media or via our support staff at https://help.keepkey.com

Thanks!
