### ISSUE TITLE
KeepKey stuck on loading accounts and balances

### ISSUE THREAD

**Issue by jackebennett91** [keepkey/keepkey-firmware#16]
I recently had my broken harddrive in a laptop replaced. I did not notice that the system time had not been set correctly, and I setup a new ETH wallet and received some 22 ETH into it. After checking that it had made it to the wallet, I realised my system time was incorrect so I changed it to automatically adjust the date and time.

Now my KeepKey client will not make it past the "loading accounts" screen after inputting my PIN. have i lost any ETH and what can I do to re-gain access to my wallets?

**Comment by ngmiller** [comment]
Closing due to age and inactivity. Users experiencing these types of issues are encouraged to open a ticket with our support staff here: https://help.keepkey.com/ Thanks!
