### ISSUE TITLE
Feature request (Testnet support LTC,ETH,BCH)

### ISSUE THREAD

**Issue by Mushroomizer** [keepkey/keepkey-firmware#175]
If possible, please look into adding support for 

- Litecoin Testnet
- Ethereum Testnet
- BitcoinCash Testnet

I Could not find a definition for them here:
 https://github.com/keepkey/keepkey-firmware/blob/0806bb7eb29df19801e116c964c54a86a0ddd911/include/keepkey/firmware/coins.def

**Comment by keepkeyjon** [comment]
Feel free to submit a PR adding them.
