### ISSUE TITLE
Support for more general output scripts

### ISSUE THREAD

**Issue by kyuupichan** [keepkey/keepkey-firmware#186]
Keepkey does not support more general output scripts for signing, only basic templates like old-style limited OP_RETURN, P2SH and P2PKH.  Bitcoin's scripting language is far more flexible and more general support would be very useful.

**Comment by keepkeyjon** [comment]
That added utility is a bit at odds with making the device simple for users to understand. I'd like to see a proposal for how to explain such scripts to a user in a way that doesn't decrease the security & ease of use of the existing setup. I have similar issues with https://github.com/keepkey/keepkey-firmware/issues/55

**Comment by mrnerdhair** [comment]
For every TX we're asked to sign we have to have a way to tell the user what it does in plain language, and that's not something that can supported in general for arbitrary scripts.
