### ISSUE TITLE
GPG Key

### ISSUE THREAD

**Issue by clehner** [keepkey/keepkey-firmware#201]
Where is the public key for B4BE6B5BA471354E5D71AC5A1A60E4FE407D43EF, which signs the git tags and binary releases? I could not find it on keyservers. @keepkeyjon

**Comment by keepkeyjon** [comment]
I gpg sign all the releases with my keys: https://api.github.com/users/keepkeyjon/gpg_keys

And then the firmware itself gets signed with a separate set of 3-of-5 secp256k1 keys.

**Comment by clehner** [comment]
Thanks @keepkeyjon.
Imported:
```
curl -s https://api.github.com/users/keepkeyjon/gpg_keys | jq -r '.[]|.raw_key' gpg_keys |gpg --import
```
