### ISSUE TITLE
idea: binary search for ETH tokens

### ISSUE THREAD

**Issue by keepkeyjon** [keepkey/keepkey-firmware#213]
Once we have: https://github.com/keepkey/python-keepkey/pull/88, we could do a binary search here instead of linear: https://github.com/keepkey/keepkey-firmware/blob/master/lib/firmware/ethereum_tokens.c#L22, which would speed up ERC20 signing. This may get more important as the size of the table grows.

Related to #68.

**Comment by BitHighlander** [comment]
this will be made obsolete by our EV protocol
