### ISSUE TITLE
Does the current KeepKey FW support FIDO U2F usage on Chrome?

### ISSUE THREAD

**Issue by brianddk** [keepkey/keepkey-firmware#233]
I see that call-outs in the Firmware, but I see some components have been removed in the library.  Can I use a KeepKey (on this FW rev) as a U2F device on `github.com` like I can with Ledger and Trezor?

**Comment by My1** [comment]
at least on the latest firnware that is released U2F works. no idea whether this revision on github is any different

**Comment by brianddk** [comment]
@My1 , Thanks... 

Closing

**Comment by My1** [comment]
no problem. and in fact the Keepkey's u2f implementation is done very interestingly.
it uses the first 44 bits of the appid SHA-256 hash (it doesnt get the appid verbatim sadly) to create a mnemnoic you can use to make sure you are signing in to the correct place which is kinda awesome
