### ISSUE TITLE
Adding Support for XinFin[XDC] Network Mainnet chain

### ISSUE THREAD

**Issue by hckhunk** [keepkey/keepkey-firmware#240]
**XinFin Network mainnet chain support**
How do we initiate support for XinFin[XDC] Network support? It is a DeFi + NFT protocol

**Added to Ethereum compatible chain list**
https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-50.json

**Comment by mrnerdhair** [comment]
Closing in favor of #247.
