### ISSUE TITLE
Failed to match source-compiled hash with released binary hash [v.4.0.0]

### ISSUE THREAD

**Issue by Annorstades** [keepkey/keepkey-firmware#25]
I Docker compiled the v.4.0.0 source code and got the sha256sum `2500d49fdd8692dca988f2998b6bc658d22ae2187e3f34b2705b635381690193`.

The sha256sum (excluding meta/sigs) of the official binary is `6350e95dea44b6e50eed67f95757fd1d543d8b13dc95b5eb38813655165583ab`.

Can anyone reproduce these? Or have I done something wrong?

**Comment by keepkeyjon** [comment]
The docker builds weren't quite fully reproducible/hermetic until: https://github.com/keepkey/keepkey-firmware/commit/c6c2c43627aa922d0506861ee3a5e02fd458b082

The issue solved there is that, despite building the docker image from the same Dockerfile, updates to various toolchain components were likely to be subtly different from how we built it, leading to different binaries. The latest release of production & beta firmwares should have that fixed going forward.

Please let me know if you are still unable to verify the hashes of v4.0.3 and v5.0.0 (latest production/beta respectively).

Jon
