### ISSUE TITLE
Please change emulator port(s)

### ISSUE THREAD

**Issue by prusnak** [keepkey/keepkey-firmware#276]
Please change emulator port(s) to something else than 21324 (and 21325 for the debug interface)

21324 (0x534c) is Trezor's USB vendor ID

You can use for example 0x2B24 which seems is yours USB vendor ID

This reveals all places where the change needs to be done:
* https://github.com/keepkey/keepkey-firmware/search?q=21324
* https://github.com/keepkey/keepkey-firmware/search?q=21325

Context: https://github.com/bitcoin-core/HWI/issues/517

**Comment by reidrankin** [comment]
Sorry we've missed this so far. This will require a little bit of coordination because the hdwallet unit tests also use the emulator, but it seems a reasonable step and I'll work on it soon.
