### ISSUE TITLE
Adding a new coin

### ISSUE THREAD

**Issue by Momo10101** [keepkey/keepkey-firmware#303]
Hello,

I would like to add a new coin to keepkey and I was wondering if there is any documentation on how to do that. Sorry if this is not the right place to ask this but i already sent an email to tech@keepkey.com and got no response.

**Comment by BitHighlander** [comment]
here is a sample pr for reference. Adding a coin is involved, here is an example https://github.com/keepkey/keepkey-firmware/pull/221/files. If we get more guides together they will be posted in the docs dir.
