### ISSUE TITLE
litecoin legacy coins no longer visible

### ISSUE THREAD

**Issue by mavigro** [keepkey/keepkey-firmware#324]
Saw coins yesterday on the official keepkey interface (https://beta.shapeshift.com/) but today they're not showing.  Electrum and Trezor show coins so it's clearly a keepkey issue with the Shapeshift interface.

My current firmware / bootloader is V7.1.8, / v.1.1.0

Noticed an update pop-up on Shapeshift about litecoin requiring the latest firmware (V7.4.0) but thet refers to segwit xpubs
https://github.com/keepkey/keepkey-firmware/releases/tag/v7.4.0

Prefer not to update firmware if unrelated.

**Comment by BitHighlander** [comment]
issues with shapeshift should be opened here. https://github.com/shapeshift/web/issues
