### ISSUE TITLE
(SPIKE)(FIRMWARE) auto launch electron app via popup?

### ISSUE THREAD

**Issue by BitHighlander** [keepkey/keepkey-firmware#333]

**Comment by BitHighlander** [comment]
Is it possible to auto launch an electron app from the firmware IF it is installed?

can it still launch keepkey.com if no app found?

**Comment by amitojsingh366** [comment]
can launch the electron app via the protocol `keepkey://` but don't think we can open the website if app not installed, possible can be done with changes to firmware?

**Comment by mrnerdhair** [comment]
You can't launch the app via webusb, but you can have the website it links to launch the app via the keepkey:// protocol.
