### ISSUE TITLE
Potential SIGHASH_FORKID issue when signing multi-sig BCH transactions

### ISSUE THREAD

**Issue by ngmiller** [keepkey/keepkey-firmware#35]
Reported in https://github.com/keepkey/python-keepkey/issues/18

**Comment by ngmiller** [comment]
@kyuupichan This section of code in the latest firmware leads me to believe that we are in fact signing with the correct SIGHASH_FORKID for BCH: https://github.com/keepkey/keepkey-firmware/blob/production/keepkey/local/baremetal/signing.c#L893-L911

Cross referencing with the coin list here: https://github.com/keepkey/keepkey-firmware/blob/production/keepkey/local/baremetal/coins.c#L33 we can see that BCH is the only coin that will return `true` for `coin->has_forkid` (the last field in the struct), so I'm leaning towards this being an issue with the client software crafting transactions, not the firmware. Let me know what you think.

**Comment by ngmiller** [comment]
fyi @bgok ^

**Comment by ngmiller** [comment]
Hi @kyuupichan. Just following up. Have you had a chance to take a look at this? Is there anyone else we should ping on this issue as well?

**Comment by kyuupichan** [comment]
I have not. Unfortunately I won't find time until January, I'm simply swamped at the moment.

I will have to go through the data being passed in carefully, compare against what is expected, and find the problem. Unfortunately I don't think the requirements are documented anywhere - if so please point me to them.

**Comment by keepkeyjon** [comment]
Following up again, were you able to pinpoint the issue?

**Comment by kyuupichan** [comment]
I have not had time to look, and I won't for several months.  It is on my list however as I want to use keepkey for such txs with Electron Cash.

Can I ask if you have any tests for signing multisig Bitcoin Cash transactions in your testsuite that produce signed transactions accepted by the network?  Electron Cash produces signed transactions with KeepKey but the signatures are rejected by Bitcoin ABC.  When it produces them signing everything itself they are accepted by the network.

If you have such tests this is probably an Electron Cash bug in its KeepKey wrapper layer and you can close this.  If you don't then it would be a nice test to add and it might uncover an issue.

**Comment by keepkeyjon** [comment]
If there was an issue here, it has most likely been fixed on `v5.8.0`. If not, please re-open with a testcase that demonstrates the issue.

**Comment by kyuupichan** [comment]
Thanks I'll give it a go soon. Trezor also fixed a bug in Electron Cash
KeepKey whilst updating the Trezor code, that may also help.

**Comment by kyuupichan** [comment]
This was definitely an issue with previous versions of the firmware, but as you note 5.8.0 fixed it (I just upgraded and retried; see https://github.com/Electron-Cash/Electron-Cash/issues/872
