### ISSUE TITLE
what if the UPDATE wipes out my KEEPKEY?

### ISSUE THREAD

**Issue by hbiglari** [keepkey/keepkey-firmware#43]
How do I recover if the UPDATE wipes out my keepkey?  Do I have the option of not updating?  Thanks ,Haik

**Comment by keepkey-support** [comment]
While this is very uncommon, please make sure you have your 12 word recovery sentence written down incase your KeepKey device is wiped. I recommend updating the firmware on your KeepKey device to benefit from the most up to date features, as you will be required to update after a certain amount of declined updates. If your device is wiped you can simply recover it using your 12 word recover sentence, but don't worry your funds will not be compromised in the case of this happening.

Please reach out to support@keepkey.com if you have any further questions or concerns!
