### ISSUE TITLE
unable to verify signature on keepkey binary tarballs

### ISSUE THREAD

**Issue by vagrantc** [keepkey/keepkey-firmware#49]
The binary tarballs appear to be signed with a key not available on public keyservers. Are the public signing keys published somewhere else?

$ gpg --verify binaries.tar.bz2.sig
gpg: assuming signed data in 'binaries.tar.bz2'
gpg: Signature made Tue 22 May 2018 04:38:13 PM UTC
gpg:                using RSA key B4BE6B5BA471354E5D71AC5A1A60E4FE407D43EF
gpg: Can't check signature: No public key

$ gpg --recv-key B4BE6B5BA471354E5D71AC5A1A60E4FE407D43EF
gpg: keyserver receive failed: No data

**Comment by keepkeyjon** [comment]
You can find my pubkeys here: https://api.github.com/users/keepkeyjon/gpg_keys
