### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by sampablokuper** [keepkey/keepkey-firmware#9]
The licensing for the code in this repository is a bit unclear:

- No licence file present at top level of repository.
- No license mentioned in the README file.

I note that some of the files in the repository have copyright and licensing notices, e.g. https://github.com/keepkey/keepkey-firmware/blob/master/keepkey_board/public/keepkey_board.h states:

> This library is free software: you can redistribute it and/or modify
> it under the terms of the GNU Lesser General Public License as published by
> the Free Software Foundation, either version 3 of the License, or
> (at your option) any later version.

However, it is unclear which files within the repository constitute the "library" mentioned there.

Please could you add a license file to the top level of the repository, and ideally also mention the license in the readme, so that the licensing is clear?

Thanks!

**Comment by dstanchfield** [comment]
There are lots of dependencies with their own licenses, so you should refer to each file for the governing license.  If no license is specified, it is GPLv3.  We will add this to our README
