### ISSUE TITLE
Custom firmware

### ISSUE THREAD

**Issue by yura-pakhuchiy** [keepkey/keepkey-firmware#97]
Is it possible to install custom firmware on a real device with current bootlader?
According to https://www.reddit.com/r/keepkey/comments/99k2x1/when_will_custom_firmware_be_resupported/ it was disabled some time ago. Was it fixed since then?

**Comment by keepkeyjon** [comment]
The support for re-enabling unsigned firmware has been merged, but there's a few more things we need to do before we can ship a new bootloader with it enabled.

**Comment by keepkeyjon** [comment]
I can't share the timeline on that, unfortunately. Feel free to develop against the emulator in the meantime.

**Comment by keepkeyjon** [comment]
The new bootloader re-allows custom firmware. Check it out here:

https://github.com/keepkey/keepkey-firmware/releases/tag/bl_v2.0.0
